In [34]:
from clean_data import clean_data
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_csv('../cars-competition/data/cars_train.csv', index_col='Id')
data.head()

,city,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,transmission,...,paint_color,lat,long,county_fips,county_name,state_fips,state_code,state_name,weather,price
Id,,,,,,,,,,,,,,,,,,,,,
559327,baltimore,2006.0,NaN,Scion tc,excellent,4 cylinders,gas,190000.0,clean,automatic,...,blue,39.287000,-76.647600,24510.0,Baltimore City,24.0,MD,Maryland,56.0,3200
1429566,carbondale,2018.0,dodge,charger sxt,NaN,NaN,gas,NaN,clean,automatic,...,NaN,37.720000,-89.215800,17077.0,Jackson,17.0,IL,Illinois,48.0,30620
931606,thumb,1997.0,ford,f 250 2 wheel dr pickup,fair,NaN,gas,NaN,clean,automatic,...,white,43.483300,-83.383500,26157.0,Tuscola,26.0,MI,Michigan,45.0,1800
1265412,laredo,2003.0,ram,NaN,NaN,8 cylinders,gas,NaN,clean,automatic,...,NaN,27.850069,-99.668883,48479.0,Webb,48.0,TX,Texas,67.0,4500
1133731,ocala,2000.0,dodge,1500,NaN,NaN,gas,NaN,clean,automatic,...,NaN,29.165000,-81.539900,12069.0,Lake,12.0,FL,Florida,65.0,1400

In [3]:
train = clean_data(data)
train.head()

Cleaning cylinders...

/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['cylinders'][data_frame['cylinders']=='other'] = median

Cleaning condition...

/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['condition'][data_frame['condition'].isnull()] = 'unknown'

Cleaning odometer...

/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['year'][((data_frame['year']<1900) | (data_frame['year'].isnull()))] = year_avg

Cleaning drive...
Cleaning size...

/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['drive'][data_frame['drive'].isnull()]='fwd'

Cleaning manufacturer...

/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['manufacturer'][data_frame['manufacturer'].isnull()] = 'unknown'
/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['fuel'][data_frame['fuel'].isnull()]='other'
/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['transmission'][data_frame['transmission'].isnull()]='other'
/home/felipe/Documents/coding/academic-kaggle-competitions/src/clean_data.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame['title_status'][data_frame['title_status'].isnull()]='clean'

Cleaning fuel...
Cleaning transmission...
Cleaning title status...
Data cleaning complete!

,city,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,transmission,...,lat,long,county_fips,county_name,state_fips,state_code,state_name,weather,price,decade
Id,,,,,,,,,,,,,,,,,,,,,
559327,baltimore,2006.0,unknown,Scion tc,2,4,gas,190000.000000,clean,automatic,...,39.287000,-76.647600,24510.0,Baltimore City,24.0,MD,Maryland,56.0,3200,200.0
1429566,carbondale,2018.0,dodge,charger sxt,0,6,gas,113584.991571,clean,automatic,...,37.720000,-89.215800,17077.0,Jackson,17.0,IL,Illinois,48.0,30620,201.0
931606,thumb,1997.0,ford,f 250 2 wheel dr pickup,0,6,gas,113584.991571,clean,automatic,...,43.483300,-83.383500,26157.0,Tuscola,26.0,MI,Michigan,45.0,1800,199.0
1265412,laredo,2003.0,ram,NaN,0,8,gas,113584.991571,clean,automatic,...,27.850069,-99.668883,48479.0,Webb,48.0,TX,Texas,67.0,4500,200.0
1133731,ocala,2000.0,dodge,1500,0,6,gas,113584.991571,clean,automatic,...,29.165000,-81.539900,12069.0,Lake,12.0,FL,Florida,65.0,1400,200.0

In [7]:
# Select only relevant columns
train = train[['year','manufacturer','condition','cylinders','fuel','odometer','title_status','transmission','drive','size','price']]

In [8]:
train.dtypes

year            float64
manufacturer     object
condition         int64
cylinders         int64
fuel             object
odometer        float64
title_status     object
transmission     object
drive            object
size             object
price             int64
dtype: object

In [12]:
# Getting dummies for categorical columns
train = pd.get_dummies(train,drop_first=True)

In [24]:
# Get X and y
X = train.drop(columns='price')
y = train['price']

In [20]:
# Feature reduction
pca = PCA(n_components = 30)
X_new = pca.fit_transform(X)

In [22]:
pd.DataFrame(X_new)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,76415.008411,1.998800,2.285007,1.191960,-0.099854,0.321351,0.250586,0.282138,0.228801,0.085054,...,0.046213,0.012245,0.056700,0.010830,-0.018227,-0.040634,0.005065,-0.061314,-0.053696,-0.022555
1,-0.000141,13.124266,-0.199016,-1.057089,-0.211036,0.099359,-0.009945,0.212206,-0.223439,-0.004828,...,-0.075092,-0.004849,0.067668,0.025229,0.001647,-0.027629,0.016420,-0.013365,-0.014848,-0.027246
2,0.000085,-7.872017,0.135497,-0.931607,-0.207106,-0.431458,0.604551,-0.441833,-0.250050,0.058381,...,-0.007957,0.001552,0.028967,0.003747,-0.000473,-0.021121,0.011932,-0.027425,-0.006553,-0.023567
3,0.000021,-1.905981,-1.837615,-0.953508,-0.262405,0.500095,0.356211,0.320651,-0.017432,0.065289,...,-0.225784,0.313321,0.211814,0.002045,-0.031306,-0.055662,-0.034075,-0.149962,-0.073508,-0.103742
4,0.000052,-4.871265,0.121437,-0.948306,-0.297413,0.083603,0.003075,0.188087,-0.201826,0.167383,...,-0.071063,-0.008757,0.072693,0.018311,0.006978,-0.023993,0.010830,-0.012585,-0.015885,-0.029642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469987,124462.008421,1.464724,-0.143388,-0.823583,0.520126,-0.980063,0.234747,-0.413296,0.551228,0.262087,...,-0.022894,-0.195963,-0.021730,0.041062,0.049429,0.049976,0.062939,0.196774,0.101577,0.065609
469988,-73068.991687,10.353331,-0.188195,0.864620,-0.784637,-0.008308,-0.004537,0.092822,-0.118973,-0.028026,...,0.126448,0.012197,-0.213774,-0.367302,0.798533,0.029603,-0.208200,0.150371,-0.058545,-0.128519
469989,38178.008308,11.514739,-2.253396,1.031317,-0.078292,-0.115303,-0.009903,0.337600,0.781235,0.233827,...,-0.138555,-0.128143,0.075904,0.052051,0.036866,0.061372,0.053745,0.182701,0.106605,0.018329
469990,-78556.991688,10.333166,2.057632,1.123872,-0.014512,0.363331,0.288333,-0.003910,0.030039,0.068471,...,0.168700,0.035581,-0.178176,-0.363620,0.787824,0.020644,-0.196443,0.156684,-0.085678,-0.112623
469991,-36922.991656,7.735390,-0.122146,-0.071766,-0.522266,0.037933,-0.002527,0.113929,-0.170372,0.019762,...,0.127711,-0.057286,-0.239120,-0.225490,-0.484709,-0.293460,-0.321450,0.583009,-0.173179,-0.121080

In [26]:
# Split train and test
X_train, X_test, y_train, y_test = train_test_split(X_new,y,test_size=0.2)

In [32]:
# Linear Regression
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
# Predict
y_pred = lin_reg.predict(X_test)

In [41]:
# Check error
mean_squared_error(y_test, y_pred)

49789430837940.18

In [40]:
# Check error
mean_squared_error(y_test, [y_test.mean()]*len(y_test))

49807462734317.516

In [29]:
# Random Forrest
regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)
regr.fit(X_train,y_train)

KeyboardInterrupt: